server:
  config:
    activate:
      on-profile: dev

spring:
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb

encrypt:
  secret:
    key: ${ENCRYPT_SECRET_KEY}